language: swift
rvm:
  - 2.4.3
os: osx
osx_image: xcode10.2

branches:
  only:
  - master
  - develop

before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - bundle exec fastlane build_for_testing
  - bundle exec fastlane run_testing
