skip_docs
default_platform(:ios)

platform :ios do
  desc "Build for Testing"
  lane :build_for_testing do
    scan(
      build_for_testing: true
    )
  end

  desc "Run Testing"
  lane :run_testing do 
  scan(
    skip_build: true
  )
  end
end
